# Jekyll configuration

name: Fierralin's Blog
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://fierralin.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/Blog'
#host: 0.0.0.0
#port: 6639

github_username: Fierralin
twitter_username: Fierralin

share:
  facebook: true
  twitter: true
  gplus: true
  email: true

social:
  github: Fierralin
  #linkedin: Fierralin
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-89053635-1 
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica: true


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
# destination: -d DIR
#destination: /srv/www/whuthering
